Add job to build wheels
sift-stack/sift pull request #120
Opened 2024-11-11 21:31 UTC by marcsiftstack

Example: https://github.com/marcsiftstack/sift-gha-test/actions/runs/11786369431/job/32829514476

TODO: figure out why Python 3.9 creates UNKNOWN package:
```
creating UNKNOWN.egg-info
writing UNKNOWN.egg-info/PKG-INFO
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
Copying UNKNOWN.egg-info to build/bdist.linux-x86_64/wheel/UNKNOWN-0.0.0-py3.9.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/UNKNOWN-0.0.0.dist-info/WHEEL
creating 'dist/UNKNOWN-0.0.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'UNKNOWN-0.0.0.dist-info/LICENSE'
adding 'UNKNOWN-0.0.0.dist-info/METADATA'
adding 'UNKNOWN-0.0.0.dist-info/WHEEL'
adding 'UNKNOWN-0.0.0.dist-info/top_level.txt'
adding 'UNKNOWN-0.0.0.dist-info/RECORD'
```

2024-11-11 23:44 UTC, niliayu requested changes

2024-11-11 23:44 UTC, niliayu commented on python/pyproject.toml
> +  "npTDMS~=1.9",
I think it'd be better to put this into a more specific `tdms` group, like I did with ssl related stuff [here](https://github.com/sift-stack/sift/blob/main/python/pyproject.toml#L63), so people can specify `sift-stack-py[tdms]` in their requirements if they need this specifically.

2024-11-12 17:21 UTC, marcsiftstack commented on .github/workflows/python_build.yaml
> +name: Build Wheels
Considering renaming this to "Create Offline Installation Archive" or something like that...open to suggesstions.

2024-11-19 19:21 UTC, niliayu commented on .github/workflows/python_build.yaml
> +        python_version: [3.9, 3.11]
Another thought I had here, any downside to doing this for all the python versions we support right now?

2024-12-31 22:14 UTC, closed without merging